### ISSUE TITLE
how do i actually use this fontset in a webpage?

### ISSUE THREAD

**Issue by khavernathy** [scottdorman/mdl2-icons#4]

**Comment by scottdorman** [comment]
There are basic instructions at https://scottdorman.github.io/mdl2-icons/get-started/.

Once you've downloaded the font and style sheet files (the simplest way is to use the download link to get a zip file, then unzip the file). Copy the files (or full directory) into your project and add the following line in your `<head>` element:

`<link rel="stylesheet" href="path/to/mdl2-icons/css/mdl2-icons.min.css">`

Be sure to replace the `path/to/mdl2-icons` portion with the correct path for your project.

Once you've done that, anywhere you want to use one of the icons, you would use the following html:

`<i class="mdl2 mdl2-accept" aria-hidden="true"></i>`

The `mdl2` class is required and combined with the second class, defines which icon will be used. The list of currently available icons is at https://scottdorman.github.io/mdl2-icons/icons/.
